/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/actions/backfill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Action Backfill */
        post: operations["action_backfill_api_v1_actions_backfill_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/actions/reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Action Reconcile */
        post: operations["action_reconcile_api_v1_actions_reconcile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/actions/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Action Run */
        post: operations["action_run_api_v1_actions_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/actions/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Action Stop
         * @description Cooperative: the Archiver checks the flag between recordings, so a
         *     fetch or encrypt in flight finishes or fails on its own rather than
         *     being torn down mid-write. The run then closes out as `aborted`.
         */
        post: operations["action_stop_api_v1_actions_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Activity */
        get: operations["get_activity_api_v1_activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Alerts */
        get: operations["get_alerts_api_v1_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Rules */
        put: operations["put_rules_api_v1_alerts_rules_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Test */
        post: operations["send_test_api_v1_alerts_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Calendar */
        get: operations["get_calendar_api_v1_calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/day": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Day
         * @description `date_` defaults to the camera's own local today, so the dashboard
         *     can open Footage without first knowing the camera's timezone.
         */
        get: operations["get_day_api_v1_day_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/day/hour": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Day Hour */
        get: operations["get_day_hour_api_v1_day_hour_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Devices */
        get: operations["list_devices_api_v1_devices_get"];
        put?: never;
        /** Add Device */
        post: operations["add_device_api_v1_devices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Discover */
        post: operations["discover_api_v1_devices_discover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/enabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Enabled */
        get: operations["list_enabled_api_v1_devices_enabled_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{device_id}/enabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Enabled */
        put: operations["set_enabled_api_v1_devices__device_id__enabled_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export */
        get: operations["export_api_v1_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/export/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview */
        get: operations["preview_api_v1_export_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/growth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Growth */
        get: operations["get_growth_api_v1_growth_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["get_health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revokes every session server-side by bumping the epoch, not just this
         *     browser's cookie: a copied cookie stops working too.
         */
        post: operations["logout_api_v1_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/problems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Problems */
        get: operations["list_problems_api_v1_problems_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/problems/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Problems Count */
        get: operations["get_problems_count_api_v1_problems_count_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recordings/{recording_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recording */
        get: operations["get_recording_api_v1_recordings__recording_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recordings/{recording_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Recording
         * @description Makes a failed recording eligible for the next run's pickup; it is
         *     not re-downloaded on the spot (see Repository.retry_recording).
         */
        post: operations["retry_recording_api_v1_recordings__recording_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recordings/{recording_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Recording */
        get: operations["stream_recording_api_v1_recordings__recording_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recordings/{recording_id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Recording */
        post: operations["verify_recording_api_v1_recordings__recording_id__verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/retention": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Retention */
        get: operations["get_retention_api_v1_retention_get"];
        /** Put Retention */
        put: operations["put_retention_api_v1_retention_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_v1_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Schedule */
        get: operations["get_schedule_api_v1_schedule_get"];
        /** Put Schedule */
        put: operations["put_schedule_api_v1_schedule_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_v1_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Public, for the Docker healthcheck, which only needs the status
         *     code. `?verbose=1` adds gateway state, per-device coverage alarms
         *     and database error text, so it needs a logged-in session: behind a
         *     reverse-proxy hostname that detail would otherwise be public.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityEventOut */
        ActivityEventOut: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Detail */
            detail: string | null;
            /** Job Id */
            job_id: string;
            /** Kind */
            kind: string;
        };
        /** ActivityOut */
        ActivityOut: {
            /** Default From */
            default_from: string;
            /** Default To */
            default_to: string;
            /** Events */
            events: components["schemas"]["ActivityEventOut"][];
            /** Max Backfill Days */
            max_backfill_days: number;
            /** Queued */
            queued: number;
            running: components["schemas"]["RunOut"] | null;
            /** Scheduler Available */
            scheduler_available: boolean;
            /** Timezone */
            timezone: string;
        };
        /**
         * AddDeviceIn
         * @description Password is `SecretStr` so an accidental `repr()` anywhere, including
         *     a structlog kwarg, renders `**********` instead of the plaintext.
         */
        AddDeviceIn: {
            /** Alias */
            alias: string;
            /** Channel */
            channel?: number | null;
            /** Host */
            host: string;
            /** Name */
            name?: string | null;
            /**
             * Password
             * Format: password
             */
            password: string;
            /** Timezone */
            timezone: string;
            /** User */
            user: string;
        };
        /**
         * AlertRules
         * @description What to alert on. Seeded from `[alerts.rules]` and editable from the
         *     dashboard, unless a `REOVAULT_ALERTS__RULES__*` env var pins it (same
         *     scheme as retention).
         */
        AlertRules: {
            /**
             * Coverage
             * @default true
             */
            coverage: boolean;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Gateway Down
             * @default true
             */
            gateway_down: boolean;
            /**
             * Gateway Down Minutes
             * @default 15
             */
            gateway_down_minutes: number;
            /**
             * Notify On Resolve
             * @default true
             */
            notify_on_resolve: boolean;
            /**
             * Problems
             * @default true
             */
            problems: boolean;
            /**
             * Renotify Hours
             * @default 24
             */
            renotify_hours: number;
            /**
             * Run Failed
             * @default true
             */
            run_failed: boolean;
        };
        /** AlertsOut */
        AlertsOut: {
            /** Channels */
            channels: components["schemas"]["ChannelOut"][];
            /** Env Pinned */
            env_pinned: boolean;
            /** Open */
            open: components["schemas"]["OpenAlertOut"][];
            rules: components["schemas"]["AlertRules"];
        };
        /** BackfillIn */
        BackfillIn: {
            /** From Local */
            from_local: string;
            /** To Local */
            to_local: string;
        };
        /** BannerOut */
        BannerOut: {
            /**
             * Level
             * @enum {string}
             */
            level: "warn" | "bad";
            /** Link */
            link?: "problems" | null;
            /** Text */
            text: string;
        };
        /** CalendarDayOut */
        CalendarDayOut: {
            /** Count */
            count: number;
            /** Date */
            date: string;
            /** Density */
            density: number;
            /** Problems */
            problems: number;
        };
        /** CalendarOut */
        CalendarOut: {
            /** Days */
            days: components["schemas"]["CalendarDayOut"][];
            /** Month */
            month: string;
            /** Today */
            today: string;
        };
        /** ChannelOut */
        ChannelOut: {
            /** Configured */
            configured: boolean;
            /** Name */
            name: string;
        };
        /** ConfirmOut */
        ConfirmOut: {
            /** Bytes */
            bytes: number;
            /** Count */
            count: number;
            /** Token */
            token: string;
        };
        /** CountOut */
        CountOut: {
            /** Count */
            count: number;
        };
        /** CoverageOut */
        CoverageOut: {
            /** Alarm */
            alarm: boolean;
            /** Margin Fraction */
            margin_fraction: number | null;
            /** Oldest On Card Utc */
            oldest_on_card_utc: string | null;
            /** Oldest Unarchived Utc */
            oldest_unarchived_utc: string | null;
        };
        /** DayOut */
        DayOut: {
            /** Available Types */
            available_types: string[];
            /** Date */
            date: string;
            /** Hours */
            hours: components["schemas"]["HourOut"][];
            /** Today */
            today: string;
            /** Total */
            total: number;
            /** Total Bytes */
            total_bytes: number;
        };
        /** DeviceOut */
        DeviceOut: {
            /** Alias */
            alias: string;
            /** Archived Bytes */
            archived_bytes: number;
            /** Archived Count */
            archived_count: number;
            /** Enabled */
            enabled: boolean;
            /** Gateway Down */
            gateway_down: boolean | null;
            /** Host */
            host: string | null;
            /** Id */
            id: number;
            last_run: components["schemas"]["RunOut"] | null;
            /** Model */
            model: string | null;
            /** Name */
            name: string | null;
            sample: components["schemas"]["StorageSampleOut"] | null;
            sd: components["schemas"]["SdBarOut"] | null;
            /** Timezone */
            timezone: string;
        };
        /**
         * DeviceSummaryOut
         * @description The navbar device switcher's row: cheap, no camera calls.
         */
        DeviceSummaryOut: {
            /** Alias */
            alias: string;
            /** Id */
            id: number;
            /** Name */
            name: string | null;
            /** Problems */
            problems: number;
            /** Timezone */
            timezone: string;
        };
        /** DevicesOut */
        DevicesOut: {
            /** Devices */
            devices: components["schemas"]["DeviceOut"][];
            /** Registry Available */
            registry_available: boolean;
        };
        /** DiscoveredOut */
        DiscoveredOut: {
            /** Already Registered */
            already_registered: boolean;
            /** Host */
            host: string;
            /** Mac */
            mac: string | null;
            /** Model */
            model: string | null;
            /** Name */
            name: string | null;
            /** Protocol */
            protocol: string | null;
            /** Uid */
            uid: string | null;
        };
        /** EnabledIn */
        EnabledIn: {
            /** Enabled */
            enabled: boolean;
        };
        /** ExportPreviewOut */
        ExportPreviewOut: {
            /** Bytes */
            bytes: number;
            /** Count */
            count: number;
        };
        /** GrowthDayOut */
        GrowthDayOut: {
            /** Bytes */
            bytes: number;
            /** Day */
            day: string;
        };
        /** GrowthOut */
        GrowthOut: {
            /** Archived Bytes */
            archived_bytes: number;
            /** Archived Count */
            archived_count: number;
            /** Avg Per Day */
            avg_per_day: number;
            /** Days */
            days: components["schemas"]["GrowthDayOut"][];
            /** Days Headroom */
            days_headroom: number | null;
            /** Vault Cap Bytes */
            vault_cap_bytes: number | null;
            /** Vault Free Bytes */
            vault_free_bytes: number | null;
            /** Vault Used Bytes */
            vault_used_bytes: number;
            /** Yearly Projection */
            yearly_projection: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            banner: components["schemas"]["BannerOut"] | null;
            coverage: components["schemas"]["CoverageOut"];
            /** Gateway Down */
            gateway_down: boolean;
            last_run: components["schemas"]["RunOut"] | null;
            /** Next Archive Utc */
            next_archive_utc: string | null;
            /** Problems Count */
            problems_count: number;
            running: components["schemas"]["RunOut"] | null;
            sample: components["schemas"]["StorageSampleOut"] | null;
            sd: components["schemas"]["SdBarOut"] | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "warn" | "bad" | "idle";
            today: components["schemas"]["TodayOut"];
        };
        /** HourOut */
        HourOut: {
            /** Bytes */
            bytes: number;
            /** Hour */
            hour: number;
            /** Total */
            total: number;
        };
        /** LoginIn */
        LoginIn: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** OpenAlertOut */
        OpenAlertOut: {
            /** Condition */
            condition: string;
            /** Device Id */
            device_id: number | null;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /** Last Sent At */
            last_sent_at: string | null;
            /** Message */
            message: string;
            /** Title */
            title: string;
        };
        /** Page[RecordingOut] */
        Page_RecordingOut_: {
            /** Items */
            items: components["schemas"]["RecordingOut"][];
            /** Next */
            next: string | null;
        };
        /** RecordingOut */
        RecordingOut: {
            /** Archived At */
            archived_at: string | null;
            /** Attempts */
            attempts: number;
            /** Ciphertext Size */
            ciphertext_size: number | null;
            /** Device Id */
            device_id: number;
            /** Duration S */
            duration_s: number | null;
            /** Id */
            id: number;
            /** Last Error */
            last_error: string | null;
            /** Last Error Class */
            last_error_class: string | null;
            /** Last Error Class Text */
            last_error_class_text: string | null;
            /** Last Error Detail */
            last_error_detail: string | null;
            /** Local Datetime */
            local_datetime: string;
            /** Local Time */
            local_time: string;
            /** Next Attempt At */
            next_attempt_at: string | null;
            /** Plaintext Sha256 */
            plaintext_sha256: string | null;
            /** Plaintext Size */
            plaintext_size: number | null;
            /** Remote Name */
            remote_name: string;
            /** Remote Size */
            remote_size: number | null;
            /**
             * Start Utc
             * Format: date-time
             */
            start_utc: string;
            /** State */
            state: string;
            /** Types */
            types: string[];
        };
        /** RetentionBody */
        RetentionBody: {
            /** Confirm */
            confirm?: string | null;
            /** Max Age Days */
            max_age_days?: number | null;
            /** Max Vault Gb */
            max_vault_gb?: number | null;
        };
        /** RetentionOut */
        RetentionOut: {
            /** Env Pinned */
            env_pinned: boolean;
            /** Max Age Days */
            max_age_days: number | null;
            /** Max Vault Gb */
            max_vault_gb: number | null;
            /** Vault Used Bytes */
            vault_used_bytes: number;
        };
        /** RetentionSaveOut */
        RetentionSaveOut: {
            confirm: components["schemas"]["ConfirmOut"] | null;
            retention: components["schemas"]["RetentionOut"];
            /** Saved */
            saved: boolean;
        };
        /** RunDetailOut */
        RunDetailOut: {
            run: components["schemas"]["RunOut"];
            /** Timezone */
            timezone: string;
        };
        /** RunOut */
        RunOut: {
            /** Bytes Archived */
            bytes_archived: number;
            /** Device Id */
            device_id: number | null;
            /** Discovered */
            discovered: number;
            /** Downloaded */
            downloaded: number;
            /** Error */
            error: string | null;
            /** Failed */
            failed: number;
            /** Finished At */
            finished_at: string | null;
            /** Id */
            id: number;
            /** Outcome */
            outcome: string | null;
            /** Skipped Dup */
            skipped_dup: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Trigger */
            trigger: string;
            /** Window From Utc */
            window_from_utc: string | null;
            /** Window To Utc */
            window_to_utc: string | null;
        };
        /** RunsOut */
        RunsOut: {
            /** Items */
            items: components["schemas"]["RunOut"][];
            /** Next */
            next: string | null;
            /** Scheduled */
            scheduled: components["schemas"]["ScheduledRunOut"][];
            /** Timezone */
            timezone: string;
        };
        /** ScheduleBody */
        ScheduleBody: {
            /** Archive Enabled */
            archive_enabled: boolean;
            /** Archive Overlap Hours */
            archive_overlap_hours: number;
            /** Archive Time */
            archive_time: string;
            /** Backfill Days */
            backfill_days: number;
            /** Backfill Dow */
            backfill_dow: number;
            /** Backfill Enabled */
            backfill_enabled: boolean;
            /** Backfill Time */
            backfill_time: string;
            /** Integrity Scan Enabled */
            integrity_scan_enabled: boolean;
            /** Integrity Scan Sample Pct */
            integrity_scan_sample_pct: number;
            /** Reconcile Enabled */
            reconcile_enabled: boolean;
            /** Reconcile Interval Hours */
            reconcile_interval_hours: number;
            /** Timezone */
            timezone?: string | null;
        };
        /** ScheduleOut */
        ScheduleOut: {
            /** Archive Enabled */
            archive_enabled: boolean;
            /** Archive Overlap Hours */
            archive_overlap_hours: number;
            /** Archive Time */
            archive_time: string;
            /** Backfill Days */
            backfill_days: number;
            /** Backfill Dow */
            backfill_dow: number;
            /** Backfill Enabled */
            backfill_enabled: boolean;
            /** Backfill Time */
            backfill_time: string;
            /** Env Pinned */
            env_pinned: boolean;
            /** Integrity Scan Enabled */
            integrity_scan_enabled: boolean;
            /** Integrity Scan Sample Pct */
            integrity_scan_sample_pct: number;
            /** Reconcile Enabled */
            reconcile_enabled: boolean;
            /** Reconcile Interval Hours */
            reconcile_interval_hours: number;
            /** Timezone */
            timezone?: string | null;
        };
        /** ScheduledRunOut */
        ScheduledRunOut: {
            /** Job */
            job: string;
            /** Label */
            label: string;
            /** Next Run Utc */
            next_run_utc: string | null;
        };
        /**
         * SdBarOut
         * @description GiB, all on the camera's own binary scale (see `sd_bar`).
         */
        SdBarOut: {
            /** Archived Gb */
            archived_gb: number;
            /** Free Gb */
            free_gb: number;
            /** Other Gb */
            other_gb: number;
            /** Total Gb */
            total_gb: number;
            /** Used Gb */
            used_gb: number;
        };
        /** SessionOut */
        SessionOut: {
            /** Authenticated */
            authenticated: boolean;
            /** Csrf Token */
            csrf_token: string;
            /** Pinned Cli Version */
            pinned_cli_version: string;
            /** Version */
            version: string;
        };
        /** StorageSampleOut */
        StorageSampleOut: {
            /** Formatted */
            formatted: boolean | null;
            /** Mounted */
            mounted: boolean | null;
            /** Remain Gb */
            remain_gb: number | null;
            /**
             * Sampled At
             * Format: date-time
             */
            sampled_at: string;
            /** Total Gb */
            total_gb: number | null;
        };
        /** TestResultOut */
        TestResultOut: {
            /** Channel */
            channel: string;
            /** Error */
            error: string | null;
            /** Ok */
            ok: boolean;
        };
        /** TodayOut */
        TodayOut: {
            /** Archived Bytes */
            archived_bytes: number;
            /** Count */
            count: number;
            /** Date */
            date: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VerifyOut */
        VerifyOut: {
            /** Ok */
            ok: boolean;
            recording: components["schemas"]["RecordingOut"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    action_backfill_api_v1_actions_backfill_post: {
        parameters: {
            query?: {
                device?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BackfillIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    action_reconcile_api_v1_actions_reconcile_post: {
        parameters: {
            query?: {
                device?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    action_run_api_v1_actions_run_post: {
        parameters: {
            query?: {
                device?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    action_stop_api_v1_actions_stop_post: {
        parameters: {
            query?: {
                device?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_activity_api_v1_activity_get: {
        parameters: {
            query?: {
                device?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_alerts_api_v1_alerts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertsOut"];
                };
            };
        };
    };
    put_rules_api_v1_alerts_rules_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertRules"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertsOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_test_api_v1_alerts_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestResultOut"][];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_calendar_api_v1_calendar_get: {
        parameters: {
            query: {
                month: string;
                device?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_day_api_v1_day_get: {
        parameters: {
            query?: {
                date_?: string | null;
                types?: string;
                device?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_day_hour_api_v1_day_hour_get: {
        parameters: {
            query: {
                date_: string;
                hour: number;
                types?: string;
                after?: string;
                device?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_RecordingOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_devices_api_v1_devices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevicesOut"];
                };
            };
        };
    };
    add_device_api_v1_devices_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddDeviceIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevicesOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    discover_api_v1_devices_discover_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoveredOut"][];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_enabled_api_v1_devices_enabled_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceSummaryOut"][];
                };
            };
        };
    };
    set_enabled_api_v1_devices__device_id__enabled_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnabledIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevicesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_v1_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    export_api_v1_export_get: {
        parameters: {
            query: {
                from_: string;
                to: string;
                types?: string;
                device?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    preview_api_v1_export_preview_get: {
        parameters: {
            query: {
                from_: string;
                to: string;
                types?: string;
                device?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportPreviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_growth_api_v1_growth_get: {
        parameters: {
            query?: {
                days?: number;
                device?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrowthOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_health_api_v1_health_get: {
        parameters: {
            query?: {
                device?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout_api_v1_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
        };
    };
    list_problems_api_v1_problems_get: {
        parameters: {
            query?: {
                after?: string;
                device?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_RecordingOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_problems_count_api_v1_problems_count_get: {
        parameters: {
            query?: {
                device?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recording_api_v1_recordings__recording_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_recording_api_v1_recordings__recording_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_recording_api_v1_recordings__recording_id__stream_get: {
        parameters: {
            query?: {
                download?: number;
            };
            header?: never;
            path: {
                recording_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_recording_api_v1_recordings__recording_id__verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_retention_api_v1_retention_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetentionOut"];
                };
            };
        };
    };
    put_retention_api_v1_retention_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetentionBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetentionSaveOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_v1_runs_get: {
        parameters: {
            query?: {
                before_id?: number | null;
                device?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_schedule_api_v1_schedule_get: {
        parameters: {
            query?: {
                device?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_schedule_api_v1_schedule_put: {
        parameters: {
            query?: {
                device?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_v1_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: {
                verbose?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
